language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  email: wenjsen@gmail.com
  api_key:
    secure: AE1n+9RlwDa34w/BIttDw+FYCdasAIW8oFraeKRLR6foAOtl+V4i97400ZnzY5kf02IDEPezx9IAmNN7yNQH1doFPNYL3kzODaluAEXOOUB6vQex2I2/R52IriS6Wg1Js5sk2T3RI7aaf47pYiUOA3bR5ZGfohBKR7YNwmoOtKKtXtXCcaz0ekf+M0i9Kvd02iVEi41b03QJjcmh1/EjTCXw5uJxAVqDMy3OH1e2YqbhdOiMt/LLOhinyyn5qZtDLClpFwdy+8WvKnoWY741w7CqjniqU+LQ08zgRcOrql4clWa7Pi31FXHr3ChRkJMZTrvUJpCNYVfE6NtSh33vGd75IxK/RddnYANb1srX4GTOkvbd3JwUa1MlAZzxCJWnYfrmvCcfMRE9f+kHKHCAqEzRCow0Q3kc/TJoXGq0cll22fkSNLg0Y9N9uUJ7UW8uGVzqXQVNxihGBwCpNjup2STxnYtJtQG3xbPrbJPOevk8wa/aLmq/zQn+w0lmjhlrBBcE5D8N4x8lJOKmE4dm/h2U+HThasJL86N1VWtGtBmaZzmIDhDC5bSWljIUPRUX5XWUPauajpd1mMQ0IYNjGJk6hn+Uwswu43wCKJFjHdYJPYWoPGuAkdWCCaKw1kt67QHBvJbZI+IdmjAy5LqbZwHeqdc3qB8yxMz1Hsj1jj0=
  skip_cleanup: true
  on:
    tags: true
    repo: wenjiasen/winston-sentry-transport
