language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  email: wenjsen@gmail.com
  api_key:
    secure: kf/EdOBe+0w7oZ85iAWzX+/dTAeyPer+WKVo9v+CY5Q1wtRdNAtweaKteUv+FZZlMiL8BBJsxE8PP0SEwTk+I6QllR4ZbC9rQA2yeQz6Oce3mxYx7dWVPfFLL9MpE+G20vV7G+SOxNDe4mGIPZ4dA030vU75VLxQvQCt6zHL1zRo9WM3nH38nLKJlgHlLu21MGWDyTXz+vbwH5m5/POfFbPML0j71+Yp+P+y2Gedx2RbRwO6wTymLi5X/aVRak4rWb3EYGqdKAURPC00h8nSskUeLOQrv7EHqoehY0DiAl742inNj/5Mmozdp28DcPCcXxoUSw8RcAzJsUCnmdD8Fu20Bx0Gti70p1NcdiMGrfKevM14iQ7NR+A4ZjeRzrbyEGPzIt75YkhotXMMB1lxtqPv1fsWhFmWKVPzoQeA0VGczDeI7vAGKhvhSvXnjPjGhL/FPxKknuOx8hpx0w4gPLE0mJvCUCBA/UwhLwW3Td8wO74soSJ5s00XxDAg29zVSd3ogU5Ex9f+GC3eNGT5IutuPDBujdpVrgY7r7wYM+YKJjmuWNd8AEqa+1qIx/dlaPscOFxTlKtNHWc27hhhuN2hzEwrCH/5dcCEkcT4fZQ4ftw4bBQnF9H6Pl49ONpozxjzzkcDVnLT1oNj7cHDFMdQrRKrQDBeQLOkiLZfUaE=
  on:
    tags: true
