language: node_js
node_js:
- '10'
script:
- npm run build
- npm run test
deploy:
  provider: npm
  email: wenjsen@gmail.com
  api_key:
    secure: sSOa62dlmteJLddNwCyqJLUHiMZyy6/wco+GSeo4LTHDwtfGN9f1+rkuOjxIgNQo0i1D5g1B/Ba3QmzPyHRfILFqNVSTgV4w0j392fGUvm7Uz+L2/YEPGMNftuTE6k21FT5ymFg62B0hwYNVU7x32BpjbuvQRHFvtC9ySwyyJ4AkTjB3JzmeUaoHLG53TY2f7FJzOTLcKDTfZMzwuAY08HU1d5MWhttnlzqsbAcN4x8ziOg0FTKC0McU0H/WquytaYZj0NL78K9dwQr8Fd+YFklMlCfAZOhMFMfpfU3D/xZ3lUuBcaGACoQ8Os56Cc6yc/B5ZK4CfWOnZjXqcx4tWAr+7W66lo4NHhX4cgOilFZkx6fKR/DRYk3M1XX3wnsf6TLvdRisXuGwUnYT8J57l0uD8PkbWNuzIktEVsviDkSApFTF0aw0e9z5ierwGS/bh98Dr3rtfP1SviOSTS698voCGVIPDrp2uuOE6xunm6WodFnS0GYfsbuKD55gcLV8KZQVBagibTt3Iqy7noarmDCQKMx6eU/RYkG1vIoli1kUfkGfiiVBIb/8Hj7/SCTYCUO9D7AwKFXJ9brLa7sCIh/g2Z+2VsP85zA917QopjXNwBCz3gjpW36DWpbwFKc3l47FsakFmo9YDwZqr3OMf6JA+BhvUEyq4w5Rpql8xwg=
  on:
    tags: true
    repo: wenjiasen/winston-sentry-transport
